import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseRequest,validateEstimate} from '../functions/estimate-nutrition/contract.mjs';
import {createHandler} from '../functions/estimate-nutrition/handler.mjs';
const input={entryId:'10000000-0000-4000-8000-000000000001',requestId:'20000000-0000-4000-8000-000000000001',revision:1,text:'2 idlis'};
const fixture=()=>({items:[{name:'Idli',portion:{quantity:2,unitKey:'pieces',kind:'COUNT',grams:null,milliliters:null,assumed:true,assumption:'Size assumed'},nutrients:{caloriesKcal:120,proteinG:4,carbsG:24,fatG:1,fiberG:null},assumptions:['Synthetic test fixture']}],explanation:'Synthetic estimate for tests only.'});
test('input bounds and identity',()=>{assert.deepEqual(parseRequest(input),input);for(const change of [{text:'x'.repeat(2001)},{revision:0},{requestId:'bad'},{text:''}])assert.throws(()=>parseRequest({...input,...change}));});
test('AI provenance is server-owned, null stays unknown, review mandatory',()=>{const raw=fixture();raw.items[0].sources=[{kind:'USDA',title:'invented'}];const result=validateEstimate(raw,'test-model',123);assert.equal(result.needsReview,true);assert.equal(result.items[0].sources[0].kind,'AI_ESTIMATE');assert.equal(result.items[0].sources[0].url,undefined);assert.equal(result.items[0].nutrients.fiberG,null);});
test('reject invalid/empty/infinite values and unexplained assumptions',()=>{for(const edit of [r=>r.items=[],r=>r.items[0].nutrients.fatG=-1,r=>r.items[0].portion.quantity=Infinity,r=>r.items[0].portion.assumption=null]){const r=fixture();edit(r);assert.throws(()=>validateEstimate(r,'model'));}});
function setup({anonymous=false,key=true,budget='reserved',providerStatus=200,providerCode=null,providerType=null,raw=fixture()}={}){
 const calls=[];
 const env=name=>({SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'server-secret',OPENAI_API_KEY:key?'provider-secret':undefined})[name];
 const fetcher=async(url,options)=>{calls.push({url,options});if(url.endsWith('/auth/v1/user'))return Response.json({id:'owner-from-auth',is_anonymous:anonymous});if(url.endsWith('/reserve_nutrition_request'))return Response.json({state:budget,result:validateEstimate(fixture(),'cached')});if(url.endsWith('/finish_nutrition_request'))return new Response(null,{status:204});if(providerCode)return Response.json({error:{code:providerCode,type:providerType,message:'private provider detail'}},{status:providerStatus});return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(raw)}]}]},{status:providerStatus});};
 return {handler:createHandler(env,fetcher),calls};
}
const request=(body=input,auth=true)=>new Request('https://test/estimate',{method:'POST',headers:auth?{Authorization:'Bearer user-token'}:{},body:JSON.stringify(body)});
test('no missing/anonymous auth reaches paid provider',async()=>{for(const opts of [{anonymous:true},{}]){const {handler,calls}=setup(opts);const r=await handler(request(input,!!opts.anonymous));assert.equal(r.status,401);assert.ok(!calls.some(c=>c.url.includes('openai')));}});
test('server owner, completed envelope, bounded structured request',async()=>{const {handler,calls}=setup();const r=await handler(request({...input,accountId:'attacker'}));assert.equal(r.status,200);const body=await r.json();assert.equal(body.requestId,input.requestId);assert.equal(body.estimate.needsReview,true);const reserve=calls.find(c=>c.url.endsWith('reserve_nutrition_request'));assert.equal(JSON.parse(reserve.options.body).p_user,'owner-from-auth');const paid=JSON.parse(calls.find(c=>c.url.includes('openai')).options.body);assert.equal(paid.store,false);assert.equal(paid.max_output_tokens,4000);assert.equal(paid.text.format.strict,true);});
test('missing key, cached, pending and throttled do not call provider',async()=>{for(const [opts,status] of [[{key:false},503],[{budget:'complete'},200],[{budget:'pending'},409],[{budget:'rate_limited'},429]]){const {handler,calls}=setup(opts);assert.equal((await handler(request())).status,status);assert.ok(!calls.some(c=>c.url.includes('openai')));}});
test('provider errors sanitized and reservation marked failed',async()=>{const {handler,calls}=setup({providerStatus:429});const r=await handler(request());assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'provider_busy'});assert.equal(JSON.parse(calls.at(-1).options.body).p_result,null);});

test('exhausted provider quota is distinct and sanitized',async()=>{const {handler}=setup({providerStatus:429,providerCode:'insufficient_quota'});const response=await handler(request());assert.deepEqual(await response.json(),{error:'provider_quota'});});

test('explicit OpenAI rate-limit code is distinguished from quota',async()=>{const {handler}=setup({providerStatus:429,providerCode:'rate_limit_exceeded'});const response=await handler(request());assert.deepEqual(await response.json(),{error:'provider_rate_limit'});});

test('billing subtype with insufficient_quota type remains quota',async()=>{const {handler}=setup({providerStatus:429,providerCode:'credit_balance_exhausted',providerType:'insufficient_quota'});const response=await handler(request());assert.deepEqual(await response.json(),{error:'provider_quota'});});
